project_id = "ivaeoagtrvjsksebnqwr"

# =============================================================================
# CONFIGURAÇÃO DE AUTENTICAÇÃO
# =============================================================================

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = false
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10

[functions.asaas-proxy]
verify_jwt = false

[functions.asaas-webhook-charges]
verify_jwt = false

[functions.evolution-proxy]
verify_jwt = false

[functions.asaas-import-charges]
verify_jwt = false
[functions.validate-certificate]
enabled = true
verify_jwt = true
import_map = "./functions/validate-certificate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate-certificate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate-certificate/*.html" ]
